version: '3.3'
services:
  docker-registry:
    
    ports:
        - '5000:5000'
    restart: always
    container_name: registry
    volumes:
        - 'C:\Users\bhupender.kumar\dockerregistry\auth:/auth'
        - 'C:\Users\bhupender.kumar\dockerregistry\certs:/certs'
        - 'C:\Users\bhupender.kumar\dockerregistry\registry:/var/lib/registry'
    environment:
        - REGISTRY_AUTH=htpasswd
        - 'REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm'
        - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
        - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
        - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    image: 'registry:2'
    
  docker-registry-ui:
    image: parabuzzle/craneoperator:latest
    ports:
    - "80:80"
    environment:
    - REGISTRY_HOST=docker-registry
    - REGISTRY_PORT=5000
    - REGISTRY_PROTOCOL=https
    - SSL_VERIFY=false
    - ALLOW_REGISTRY_LOGIN=true
    restart: always
    depends_on:
    - docker-registry
